"""Rule-based theme baseline for Zepto VOC Engine."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any

from src.analysis.sampler import stratified_sample, is_discovery_candidate
from src.analysis.validators import validate_themes, validate_unmet_needs
from src.config import ANALYSIS_SAMPLE_CAP, PROCESSED_DIR
from src.ingestion.schema import NormalizedReview

THEME_RULES: list[dict[str, Any]] = [
    {
        "theme_id": "t1",
        "label": "Habitual repeat buying of daily essentials",
        "pattern": re.compile(
            r"habit|routine|everyday|every day|daily|weekly|repeat|order again|always order|milk|eggs|bread",
            re.I,
        ),
        "description": (
            "Users treat Zepto as a fast replenishment tool, repeatedly ordering identical items "
            "from familiar categories (like dairy, bread) out of pure habit rather than browsing or exploring new aisles."
        ),
    },
    {
        "theme_id": "t2",
        "label": "Barrier to exploration: lack of trusted product details",
        "pattern": re.compile(
            r"expiry|date|freshness|trust|rotten|detail|ingredients|specification|nykaa|amazon|local vendor",
            re.I,
        ),
        "description": (
            "Missing key information—such as product expiry dates, manufacture dates, and detailed lists of ingredients—prevents "
            "users from experimenting with fresh foods or premium cosmetics, causing them to stick to dedicated competitors."
        ),
    },
    {
        "theme_id": "t3",
        "label": "Frustration with rigid open-box and refund policies",
        "pattern": re.compile(
            r"refund|open box|refused|OTP|missing|rotten|tomatoes|support|customer care|robbery",
            re.I,
        ),
        "description": (
            "Zepto's strict 'Open Box' validation policy (where sharing the OTP forfeits missing-item claims) creates "
            "severe frustration when delivery riders rush users or when items are missing inside sealed packages."
        ),
    },
    {
        "theme_id": "t4",
        "label": "Irrelevant homepage and cart search recommendations",
        "pattern": re.compile(
            r"recommend|recommendation|sponsored|banner|homepage|suggest|suggests|search|irrelevant|annoying",
            re.I,
        ),
        "description": (
            "Recommendations on the homepage and inside the checkout cart feel pushed, sponsored, or highly irrelevant "
            "(e.g., suggesting detergent when buying tea), failing to guide users toward organic discovery."
        ),
    },
    {
        "theme_id": "t5",
        "label": "Quick checkout convenience surfaces late-night snack segment",
        "pattern": re.compile(
            r"night|snack|chips|late|10 min|10 minutes|delivery speed|fast|bachelor|lifesaver|dopamine",
            re.I,
        ),
        "description": (
            "Superfast 10-minute delivery drives late-night snacking impulse orders among bachelors and students. "
            "This highly experiment-prone segment will purchase new snack items but rarely shops for household essentials."
        ),
    },
]

UNMET_PATTERN = re.compile(
    r"i wish|i want|why can't|why cant|bring back|please add|stop recommending|"
    r"let us|give us|option to|improve|show expiry|missing|need",
    re.I,
)


def _best_quote(review: NormalizedReview, max_len: int = 180) -> str:
    body = review.body.strip()
    if len(body) <= max_len:
        return body
    trimmed = body[:max_len]
    if " " in trimmed:
        return trimmed.rsplit(" ", 1)[0]
    return trimmed


def _match_reviews(reviews: list[NormalizedReview], pattern: re.Pattern[str], limit: int = 40) -> list[NormalizedReview]:
    matched: list[NormalizedReview] = []
    for review in reviews:
        if pattern.search(review.body):
            matched.append(review)
    matched.sort(key=lambda r: (r.rating, -len(r.body)))
    return matched[:limit]


def _build_summary(label: str, description: str, count: int) -> str:
    return (
        f"'{label}' was detected across {count} analyzed customer reviews in this run. "
        f"{description} "
        "This summary was generated by the keyword-clustering baseline (offline mode). "
        "To get advanced LLM-refined summaries, ensure GROQ_API_KEY is configured in your .env and run the pipeline."
    )


def stage_d_segments(sample: list[NormalizedReview]) -> list[dict]:
    # We will import this dynamically from pipeline to avoid circular imports
    from src.analysis.pipeline import stage_d_segments as get_segments
    return get_segments(sample)


def run_rule_baseline(
    reviews: list[NormalizedReview],
    seed: int = 42,
    sample_cap: int | None = None,
) -> dict[str, Any]:
    cap = sample_cap or min(ANALYSIS_SAMPLE_CAP, 450)
    sample_result = stratified_sample(reviews, total_cap=cap, seed=seed)
    sample = sample_result.reviews
    discovery = [r for r in sample if is_discovery_candidate(r.body)]
    pool = discovery if len(discovery) >= 15 else sample
    corpus = {r.review_id: r for r in sample}

    themes: list[dict] = []
    used_ids: set[str] = set()

    for rule in THEME_RULES:
        matched = _match_reviews(pool, rule["pattern"])
        matched = [r for r in matched if r.review_id not in used_ids]
        if not matched:
            continue
        rids = [r.review_id for r in matched[:25]]
        used_ids.update(rids)
        quote_reviews = matched[:3]
        themes.append(
            {
                "theme_id": rule["theme_id"],
                "label": rule["label"],
                "description": rule["description"],
                "supporting_review_ids": rids,
                "summary": _build_summary(rule["label"], rule["description"], len(matched)),
                "quotes": [
                    {"review_id": r.review_id, "text": _best_quote(r)} for r in quote_reviews
                ],
                "word_count": 0,
            }
        )
        themes[-1]["word_count"] = len(themes[-1]["summary"].split())
        if len(themes) >= 5:
            break

    unmet_rows: list[dict] = []
    for review in pool:
        if UNMET_PATTERN.search(review.body):
            unmet_rows.append(review)
    unmet_rows.sort(key=lambda r: r.rating)
    unmet_needs: list[dict] = []
    for rank, review in enumerate(unmet_rows[:5], start=1):
        stmt = _best_quote(review, max_len=120)
        unmet_needs.append(
            {
                "rank": rank,
                "statement": stmt,
                "supporting_review_ids": [review.review_id],
            }
        )

    segments = stage_d_segments(sample)
    theme_validation = validate_themes(themes, corpus)
    unmet_validation = validate_unmet_needs(unmet_needs, corpus)

    run_metadata = {
        "run_id": datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ"),
        "prompt_version": "rule_baseline_v1",
        "model_id": "rule-based-keyword-cluster",
        "seed": seed,
        "sample_size": len(sample),
        "unmet_subset_size": len(unmet_rows),
        "groq_call_count": 0,
        "estimated_tokens": 0,
        "cell_counts": sample_result.cell_counts,
        "theme_validation_ok": theme_validation.ok,
        "theme_validation_errors": theme_validation.errors,
        "unmet_validation_ok": unmet_validation.ok,
        "unmet_validation_errors": unmet_validation.errors,
    }

    return {
        "themes": themes,
        "unmet_needs": unmet_needs,
        "segments": segments,
        "run_metadata": run_metadata,
    }
